### PR TITLE
Improved OS and browser detection

### PR DESCRIPTION
**Pull request by IzzySoft**
As antirez doesn't seem to process pull requests, I decided to fork from you instead (to have the Yandex stuff integrated as well). I'm not a C programmer, but patching browser and OS strings doesn't really require programming knowledge :)

So I've extended the list of known OSes (there were several since 2006, especially in the mobile sector) and known agents (especially mobile ones again, including eBook readers e.g. accessing sites which provide [OPDS](https://en.wikipedia.org/wiki/OPDS) support – plenty of them on my ebook server – but also a bunch of spiders, plus newer MSIEs). Finally, I've updated `README.md` to reflect those changes – so it's easy to spot the differences between the fork and antirez's original, no longer maintained code.

All split into separate commits in case you prefer to cherry-pick. Hope you like and accept this contribution!

**Update:** your commit 0cb5c7c broke Graphviz support (see [my comment there on line 3595](https://github.com/xlab/visitors/commit/0cb5c7c756b27dee0a7f57145f61a1cca7992851#diff-0ed77933de33cec750d78b8573818c8dR3595): you assigned the `-V` cli arg to `yandex-keyphrases`, so it became a double assignment, overriding the original one for Graphviz). I took the freedom to revert this one character (replacing it by `\0`, effectively leaving the long version of the cli arg only). Fixed it for me; if you want to re-assign a short key, please pick one not yet in use :)

### CODE REVIEW

**Comment by xlab** [comment]
>  I took the freedom to revert this one character (replacing it by \0, effectively leaving the long version of the cli arg only)

It's alright, I had no right to override these flags, sorry about this.
Thanks for keeping the device/os signatures up to date.

**Comment by IzzySoft** [comment]
Glad you like it – and as for the `V`, I guess it just "slipped through" without you noticing it (other than with replacing the `X` – but for that I never understood why antirez didn't chose the `E` for "404 errors" from the beginning: there is no "X" in "errors", nor in "404". Maybe the association was "page does not eXist"). I had even preferred a `-4` here, leaving the letter free for other use :)

Expect another PR within the next 24h: more OS and UA updates, plus adding the missing TITLE attribute is on its way. I won't add all existing UAs, so I currently walk over my logs (8 sites) using `grep` and `awk` to isolate the more frequent ones. Horrible discovery: are there any humans left outside? At least 50% of all accesses are bots (crawlers/spiders) …

**Comment by xlab** [comment]
Yeah the flag naming for this tool is quite strange, so I never bothered to choose anything wise here, it's a lot of flags defined already also, I'd rather prefer a config file.

**Comment by IzzySoft** [comment]
Thought that as well. I'm no C dev, so I cannot do that; in case additional options are needed, it should be considered to make them "config only" (and before someone uses `-C` for something else, it seems like that has been reserved for exactly this purpose: passing a config file name; long version `--config` of course is free as well). All existing options could remain (for compatibility) and would, if set, override corresponding config settings.

I'd hail that – as each time I look into my script I have to figure what all those letters' meanings …

I've also thought of having the UA/OS definitions in a separate file (so no compile required) – but one nice thing about visitors is: no extra files needed to drag along, so no guessing on where to place them – a single binary, and that's it. Though with a config file passed at command-line, that could be overridden as well.

**Pull request merged**
